version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='antade0_service_manager'
      - MYSQL_USER='antade0_service_manager'
      - MYSQL_PASSWORD='AN###thony85'
      - MYSQL_ROOT_PASSWORD='AN###thony85'
      - MYSQL_HOST='mysql.freehostia.com'
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db