# Generated by Django 3.2.4 on 2021-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The customer's name", max_length=250)),
                ('email', models.EmailField(help_text='user valid email address', max_length=100)),
                ('phone', models.CharField(help_text='user valid phone number', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name="date customer's account was created")),
                ('time_created', models.TimeField(auto_now_add=True, verbose_name="time customer's account was created")),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="date customer's account was created")),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The staff's name", max_length=250)),
                ('email', models.EmailField(help_text='staff valid email address', max_length=100)),
                ('phone', models.CharField(help_text='staff valid phone number', max_length=100)),
                ('department', models.CharField(help_text='departmen of the staff', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name="date staff's account was created")),
                ('time_created', models.TimeField(auto_now_add=True, verbose_name="time staff's account was created")),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="date staff's account was created")),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name=' holiday date when services cannot be booked')),
                ('description', models.TextField(help_text='Brief description about this holiday')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this service', max_length=100)),
                ('description', models.CharField(help_text='The service description. What this service is all about', max_length=100)),
                ('duration', models.FloatField(verbose_name='The duration in minues required for task completion')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date service is created')),
                ('time_created', models.TimeField(auto_now_add=True, verbose_name='time service is created')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='date and time service is updated')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.BigIntegerField(verbose_name='the service Id linked to this order')),
                ('customer_id', models.BigIntegerField(verbose_name='the customer Id linked to this order')),
                ('employee_id', models.BigIntegerField(verbose_name='the emplyee Id assigned to treat this order')),
                ('description', models.TextField(help_text='The order descriptions')),
                ('duration', models.FloatField(verbose_name='The duration in minues required for task completion')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date order is created')),
                ('time_created', models.TimeField(auto_now_add=True, verbose_name='time order is created')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='date and time order is updated')),
            ],
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['date_created'], name='api_workord_date_cr_4d418a_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['id'], name='api_workord_id_89db5c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['date_created'], name='api_service_date_cr_35573f_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['id'], name='api_service_id_2f1f59_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='api_holiday_date_1a4423_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['id'], name='api_employe_id_de9f32_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['date_created'], name='api_custome_date_cr_b4a3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['id'], name='api_custome_id_2c695e_idx'),
        ),
    ]
