# Generated by Django 3.2.4 on 2021-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='customer_email',
            field=models.EmailField(default='', help_text="The customer's email address", max_length=100),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer_email'], name='api_workord_custome_3de53f_idx'),
        ),
    ]
