# Generated by Django 3.2.4 on 2021-06-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210628_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(help_text='Setting name', max_length=250)),
                ('value', models.CharField(help_text='value of the setting', max_length=250)),
            ],
        ),
        migrations.AddIndex(
            model_name='appsettings',
            index=models.Index(fields=['setting'], name='api_appsett_setting_203a94_idx'),
        ),
    ]
