# Generated by Django 3.2.4 on 2021-06-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210629_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='deleted',
            field=models.BigIntegerField(default=0, verbose_name='A field to track deleted request to effect reassignment'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='done',
            field=models.BigIntegerField(default=0, verbose_name='Will be 1 when service request is done'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['deleted'], name='api_workord_deleted_6d0c74_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['done'], name='api_workord_done_44c828_idx'),
        ),
    ]
