# Generated by Django 3.2.4 on 2021-06-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210629_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='end_time',
            field=models.TimeField(default=None, verbose_name='The time the order is scheduled to end'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='start_time',
            field=models.TimeField(default=None, verbose_name='The actual time the order is scheduled to start'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='deleted',
            field=models.BigIntegerField(default=0, verbose_name='A field to track deleted request> this request will be available for audit purposes'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['start_time'], name='api_workord_start_t_af2ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['end_time'], name='api_workord_end_tim_da5de8_idx'),
        ),
    ]
