# Generated by Django 3.2.4 on 2021-06-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210629_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='end_time',
            field=models.TimeField(auto_now_add=True, verbose_name='The time the order is scheduled to end'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_time',
            field=models.TimeField(auto_now_add=True, verbose_name='The actual time the order is scheduled to start'),
        ),
    ]
