# Generated by Django 3.2.4 on 2021-06-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210630_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='end_time_value',
            field=models.FloatField(default=None, verbose_name='number representation of end time'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='start_time_value',
            field=models.FloatField(default=None, verbose_name='number representation of starr time'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='end_time',
            field=models.CharField(default=None, max_length=100, verbose_name='The time the order is scheduled to end'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_time',
            field=models.CharField(default=None, max_length=100, verbose_name='The actual time the order is scheduled to start'),
        ),
    ]
