# Generated by Django 3.2.4 on 2021-06-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210630_1237'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workorder',
            name='api_workord_custome_3de53f_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='api_workord_start_t_af2ca3_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='api_workord_end_tim_da5de8_idx',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='customer_email',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer_id',
            field=models.EmailField(default='', help_text="The customer's email address", max_length=100),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer_id'], name='api_workord_custome_2f120d_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['start_time_value'], name='api_workord_start_t_08ff94_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['end_time_value'], name='api_workord_end_tim_191055_idx'),
        ),
    ]
