# Generated by Django 3.2.4 on 2021-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210630_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='start_time_value',
            field=models.FloatField(default=None, verbose_name='number representation of starr time'),
        ),
    ]
