# Generated by Django 3.2.5 on 2021-07-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_service_start_time_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='end_date',
            field=models.CharField(default=None, max_length=100, verbose_name='The date the service request ends'),
        ),
    ]
